# Generated by Django 4.2.9 on 2024-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="type_of_food",
            field=models.IntegerField(
                choices=[(0, "Bajoran"), (1, "Klingon"), (2, "Talaxian"), (3, "Mix")],
                default=3,
            ),
        ),
    ]
