# Generated by Django 4.2.9 on 2024-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_alter_food_type_of_food"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drinks",
            fields=[
                ("drink_id", models.AutoField(primary_key=True, serialize=False)),
                ("drink_name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=200, unique=True)),
                ("price", models.FloatField()),
                (
                    "type_of_drink",
                    models.IntegerField(
                        choices=[
                            (0, "Ales"),
                            (1, "Wines"),
                            (2, "Coffees"),
                            (3, "Teas"),
                        ],
                        default=3,
                    ),
                ),
                ("available", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-type_of_drink"],
            },
        ),
    ]
